# Generated by Django 6.0.4 on 2026-06-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default='Wedding', max_length=50),
        ),
    ]
